openapi: 3.0.0
info:
  title: Todo List API
  version: 1.0.0
  description: API for managing tasks in a todo list
  
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        completed:
          type: boolean

paths:
  /tasks:
    get:
      summary: Get all tasks
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              example:
                - id: 1
                  title: Buy groceries
                  completed: false
                - id: 2
                  title: Pay bills
                  completed: true

    post:
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            example:
              title: New Task
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              example:
                id: 3
                title: New Task
                completed: false

  /tasks/{task_id}:
    parameters:
      - in: path
        name: task_id
        required: true
        schema:
          type: integer

    get:
      summary: Get a specific task
      responses:
        '200':
          description: Task details
          content:
            application/json:
              example:
                id: 1
                title: Buy groceries
                completed: false

    delete:
      summary: Delete a task
      responses:
        '204':
          description: Task deleted successfully
